name: CI Runner
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: maven
      - name: Verify Java Version
        run: java -version
      - name: Clean Build
        run: ./mvnw clean compile --file pom.xml
      - name: Unit Test
        run: ./mvnw test --file pom.xml
      - name: Style format
        run: ./mvnw spotless:check --file pom.xml
      - name: Packaging Application
        run: ./mvnw package -DskipTests --file pom.xml
      - name: Upload JAR File
        uses: actions/upload-artifact@v4
        with:
          name: application jar
          path: target/*.jar
          retention-days: 30


